// Code generated by protoc-gen-gin-http. DO NOT EDIT.
package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
)

import (
	"github.com/zngue/zng_app/db/api"
	"context"
	"github.com/zngue/zng_app/pkg/validate"
	"github.com/zngue/zng_app/pkg/bind"
	"github.com/gin-gonic/gin"
)

// 注册服务
func RegisterUserGinServer(router *gin.RouterGroup, srv UserGinHttpService) *UserGinHttpRouterService {
	return NewUserGinHttpRouterService(router, srv)
}

// 服务操作
const OperationGinUserList = "api.user.v1.User.List"
const OperationGinUserCreate = "api.user.v1.User.Create"
const OperationGinUserUpdate = "api.user.v1.User.Update"
const OperationGinUserDelete = "api.user.v1.User.Delete"
const OperationGinUserInfo = "api.user.v1.User.Info"
const OperationGinUserUpdateStatus = "api.user.v1.User.UpdateStatus"

// 服务url
const OperationGinUrlUserList = "/v1/user/list"
const OperationGinUrlUserCreate = "/v1/user/create"
const OperationGinUrlUserUpdate = "/v1/user/update"
const OperationGinUrlUserDelete = "/v1/user/delete"
const OperationGinUrlUserInfo = "/v1/user/info"
const OperationGinUrlUserUpdateStatus = "/v1/user/update_status"

//服务接口用户服务

type UserGinHttpService interface {
	List(ctx context.Context, req *ListUserRequest) (rs *ListUserReply, err error)
	Create(ctx context.Context, req *CreateUserRequest) (rs *empty.Empty, err error)
	Update(ctx context.Context, req *UpdateUserRequest) (rs *empty.Empty, err error)
	Delete(ctx context.Context, req *DeleteUserRequest) (rs *empty.Empty, err error)
	Info(ctx context.Context, req *InfoUserRequest) (rs *InfoUserReply, err error)
	UpdateStatus(ctx context.Context, req *UpdateStatusUserRequest) (rs *empty.Empty, err error)
}
type UserGinHttpRouterService struct {
	srv    UserGinHttpService
	router *gin.RouterGroup
}

//服务注册用户服务

func (s *UserGinHttpRouterService) Register() {
	s.router.GET(OperationGinUrlUserList, _User_List0_GIN_HTTP_Handler(s.srv))
	s.router.POST(OperationGinUrlUserCreate, _User_Create0_GIN_HTTP_Handler(s.srv))
	s.router.POST(OperationGinUrlUserUpdate, _User_Update0_GIN_HTTP_Handler(s.srv))
	s.router.POST(OperationGinUrlUserDelete, _User_Delete0_GIN_HTTP_Handler(s.srv))
	s.router.GET(OperationGinUrlUserInfo, _User_Info0_GIN_HTTP_Handler(s.srv))
	s.router.POST(OperationGinUrlUserUpdateStatus, _User_UpdateStatus0_GIN_HTTP_Handler(s.srv))
}
func NewUserGinHttpRouterService(router *gin.RouterGroup, srv UserGinHttpService) *UserGinHttpRouterService {
	return &UserGinHttpRouterService{
		srv:    srv,
		router: router,
	}
}

func _User_List0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  ListUserRequest
			err error
			rs  *ListUserReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserList)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserList)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.List(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _User_Create0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CreateUserRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserCreate)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserCreate)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.Create(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _User_Update0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  UpdateUserRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserUpdate)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserUpdate)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.Update(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _User_Delete0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  DeleteUserRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserDelete)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserDelete)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.Delete(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _User_Info0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  InfoUserRequest
			err error
			rs  *InfoUserReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserInfo)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserInfo)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.Info(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _User_UpdateStatus0_GIN_HTTP_Handler(srv UserGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  UpdateStatusUserRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		c.Set("operation", OperationGinUserUpdateStatus)
		ctx := c.Request.Context()
		ctx = context.WithValue(ctx, "operation", OperationGinUserUpdateStatus)
		ctx = context.WithValue(ctx, "gin_ctx", c)
		ctx, err = bind.GetMiddleWires(ctx)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		rs, err = srv.UpdateStatus(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}
