// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/user/v1/user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserRequestMultiError, or nil if none found.
func (m *ListUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListUserRequestMultiError(errors)
	}

	return nil
}

// ListUserRequestMultiError is an error wrapping multiple validation errors
// returned by ListUserRequest.ValidateAll() if the designated constraints
// aren't met.
type ListUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserRequestMultiError) AllErrors() []error { return m }

// ListUserRequestValidationError is the validation error returned by
// ListUserRequest.Validate if the designated constraints aren't met.
type ListUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserRequestValidationError) ErrorName() string { return "ListUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = ListUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserRequestValidationError{}

// Validate checks the field values on ListUserReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListUserReplyMultiError, or
// nil if none found.
func (m *ListUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListUserReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListUserReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListUserReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListUserReplyMultiError(errors)
	}

	return nil
}

// ListUserReplyMultiError is an error wrapping multiple validation errors
// returned by ListUserReply.ValidateAll() if the designated constraints
// aren't met.
type ListUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserReplyMultiError) AllErrors() []error { return m }

// ListUserReplyValidationError is the validation error returned by
// ListUserReply.Validate if the designated constraints aren't met.
type ListUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserReplyValidationError) ErrorName() string { return "ListUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = ListUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserReplyValidationError{}

// Validate checks the field values on InfoUserItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *InfoUserItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InfoUserItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InfoUserItemMultiError, or
// nil if none found.
func (m *InfoUserItem) ValidateAll() error {
	return m.validate(true)
}

func (m *InfoUserItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Phone

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for Sex

	// no validation rules for Avatar

	if len(errors) > 0 {
		return InfoUserItemMultiError(errors)
	}

	return nil
}

// InfoUserItemMultiError is an error wrapping multiple validation errors
// returned by InfoUserItem.ValidateAll() if the designated constraints aren't met.
type InfoUserItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InfoUserItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InfoUserItemMultiError) AllErrors() []error { return m }

// InfoUserItemValidationError is the validation error returned by
// InfoUserItem.Validate if the designated constraints aren't met.
type InfoUserItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InfoUserItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InfoUserItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InfoUserItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InfoUserItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InfoUserItemValidationError) ErrorName() string { return "InfoUserItemValidationError" }

// Error satisfies the builtin error interface
func (e InfoUserItemValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = InfoUserItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InfoUserItemValidationError{}

// Validate checks the field values on UserDB with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserDB) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDB with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UserDBMultiError, or nil if none found.
func (m *UserDB) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDB) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Phone

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for Sex

	// no validation rules for Avatar

	if len(errors) > 0 {
		return UserDBMultiError(errors)
	}

	return nil
}

// UserDBMultiError is an error wrapping multiple validation errors returned by
// UserDB.ValidateAll() if the designated constraints aren't met.
type UserDBMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDBMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDBMultiError) AllErrors() []error { return m }

// UserDBValidationError is the validation error returned by UserDB.Validate if
// the designated constraints aren't met.
type UserDBValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDBValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDBValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDBValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDBValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDBValidationError) ErrorName() string { return "UserDBValidationError" }

// Error satisfies the builtin error interface
func (e UserDBValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = UserDBValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDBValidationError{}

// Validate checks the field values on CreateUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserRequestMultiError, or nil if none found.
func (m *CreateUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 20 {
		var err error

		err = CreateUserRequestValidationError{
			field:  "name",
			reason: "的长度必须介于 1 和 20 之间",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPhone()); l < 1 || l > 11 {
		var err error

		err = CreateUserRequestValidationError{
			field:  "phone",
			reason: "的长度必须介于 1 和 11 之间",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sex

	// no validation rules for Avatar

	if len(errors) > 0 {
		return CreateUserRequestMultiError(errors)
	}

	return nil
}

// CreateUserRequestMultiError is an error wrapping multiple validation errors
// returned by CreateUserRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserRequestMultiError) AllErrors() []error { return m }

// CreateUserRequestValidationError is the validation error returned by
// CreateUserRequest.Validate if the designated constraints aren't met.
type CreateUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserRequestValidationError) ErrorName() string {
	return "CreateUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = CreateUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserRequestValidationError{}

// Validate checks the field values on CreateUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserReplyMultiError, or nil if none found.
func (m *CreateUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateUserReplyMultiError(errors)
	}

	return nil
}

// CreateUserReplyMultiError is an error wrapping multiple validation errors
// returned by CreateUserReply.ValidateAll() if the designated constraints
// aren't met.
type CreateUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserReplyMultiError) AllErrors() []error { return m }

// CreateUserReplyValidationError is the validation error returned by
// CreateUserReply.Validate if the designated constraints aren't met.
type CreateUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserReplyValidationError) ErrorName() string { return "CreateUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e CreateUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = CreateUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserReplyValidationError{}

// Validate checks the field values on UpdateUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserRequestMultiError, or nil if none found.
func (m *UpdateUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		var err error

		err = UpdateUserRequestValidationError{
			field:  "id",
			reason: "的值必须大于0",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetName()); l < 1 || l > 20 {
		var err error

		err = UpdateUserRequestValidationError{
			field:  "name",
			reason: "的长度必须介于 1 和 20 之间",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetPhone()); l < 1 || l > 11 {
		var err error

		err = UpdateUserRequestValidationError{
			field:  "phone",
			reason: "的长度必须介于 1 和 11 之间",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Sex

	// no validation rules for Avatar

	if len(errors) > 0 {
		return UpdateUserRequestMultiError(errors)
	}

	return nil
}

// UpdateUserRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateUserRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserRequestMultiError) AllErrors() []error { return m }

// UpdateUserRequestValidationError is the validation error returned by
// UpdateUserRequest.Validate if the designated constraints aren't met.
type UpdateUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserRequestValidationError) ErrorName() string {
	return "UpdateUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = UpdateUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserRequestValidationError{}

// Validate checks the field values on UpdateUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateUserReplyMultiError, or nil if none found.
func (m *UpdateUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return UpdateUserReplyMultiError(errors)
	}

	return nil
}

// UpdateUserReplyMultiError is an error wrapping multiple validation errors
// returned by UpdateUserReply.ValidateAll() if the designated constraints
// aren't met.
type UpdateUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateUserReplyMultiError) AllErrors() []error { return m }

// UpdateUserReplyValidationError is the validation error returned by
// UpdateUserReply.Validate if the designated constraints aren't met.
type UpdateUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateUserReplyValidationError) ErrorName() string { return "UpdateUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e UpdateUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = UpdateUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateUserReplyValidationError{}

// Validate checks the field values on DeleteUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteUserRequestMultiError, or nil if none found.
func (m *DeleteUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		var err error

		err = DeleteUserRequestValidationError{
			field:  "id",
			reason: "的值必须大于0",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteUserRequestMultiError(errors)
	}

	return nil
}

// DeleteUserRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteUserRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteUserRequestMultiError) AllErrors() []error { return m }

// DeleteUserRequestValidationError is the validation error returned by
// DeleteUserRequest.Validate if the designated constraints aren't met.
type DeleteUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteUserRequestValidationError) ErrorName() string {
	return "DeleteUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = DeleteUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteUserRequestValidationError{}

// Validate checks the field values on InfoUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InfoUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InfoUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InfoUserRequestMultiError, or nil if none found.
func (m *InfoUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InfoUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		var err error

		err = InfoUserRequestValidationError{
			field:  "id",
			reason: "的值必须大于0",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return InfoUserRequestMultiError(errors)
	}

	return nil
}

// InfoUserRequestMultiError is an error wrapping multiple validation errors
// returned by InfoUserRequest.ValidateAll() if the designated constraints
// aren't met.
type InfoUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InfoUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InfoUserRequestMultiError) AllErrors() []error { return m }

// InfoUserRequestValidationError is the validation error returned by
// InfoUserRequest.Validate if the designated constraints aren't met.
type InfoUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InfoUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InfoUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InfoUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InfoUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InfoUserRequestValidationError) ErrorName() string { return "InfoUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e InfoUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = InfoUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InfoUserRequestValidationError{}

// Validate checks the field values on InfoUserReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *InfoUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InfoUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InfoUserReplyMultiError, or
// nil if none found.
func (m *InfoUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *InfoUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Phone

	// no validation rules for Sex

	// no validation rules for Avatar

	if len(errors) > 0 {
		return InfoUserReplyMultiError(errors)
	}

	return nil
}

// InfoUserReplyMultiError is an error wrapping multiple validation errors
// returned by InfoUserReply.ValidateAll() if the designated constraints
// aren't met.
type InfoUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InfoUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InfoUserReplyMultiError) AllErrors() []error { return m }

// InfoUserReplyValidationError is the validation error returned by
// InfoUserReply.Validate if the designated constraints aren't met.
type InfoUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InfoUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InfoUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InfoUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InfoUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InfoUserReplyValidationError) ErrorName() string { return "InfoUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e InfoUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = InfoUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InfoUserReplyValidationError{}

// Validate checks the field values on UpdateStatusUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateStatusUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateStatusUserRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateStatusUserRequestMultiError, or nil if none found.
func (m *UpdateStatusUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateStatusUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		var err error

		err = UpdateStatusUserRequestValidationError{
			field:  "id",
			reason: "的值必须大于0",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetStatus() <= 0 {
		var err error

		err = UpdateStatusUserRequestValidationError{
			field:  "status",
			reason: "的值必须大于0",
		}

		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UpdateStatusUserRequestMultiError(errors)
	}

	return nil
}

// UpdateStatusUserRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateStatusUserRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateStatusUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateStatusUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateStatusUserRequestMultiError) AllErrors() []error { return m }

// UpdateStatusUserRequestValidationError is the validation error returned by
// UpdateStatusUserRequest.Validate if the designated constraints aren't met.
type UpdateStatusUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateStatusUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateStatusUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateStatusUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateStatusUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateStatusUserRequestValidationError) ErrorName() string {
	return "UpdateStatusUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateStatusUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = UpdateStatusUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateStatusUserRequestValidationError{}

// Validate checks the field values on UpdateStatusUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateStatusUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateStatusUserReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateStatusUserReplyMultiError, or nil if none found.
func (m *UpdateStatusUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateStatusUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return UpdateStatusUserReplyMultiError(errors)
	}

	return nil
}

// UpdateStatusUserReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateStatusUserReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateStatusUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateStatusUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateStatusUserReplyMultiError) AllErrors() []error { return m }

// UpdateStatusUserReplyValidationError is the validation error returned by
// UpdateStatusUserReply.Validate if the designated constraints aren't met.
type UpdateStatusUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateStatusUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateStatusUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateStatusUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateStatusUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateStatusUserReplyValidationError) ErrorName() string {
	return "UpdateStatusUserReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateStatusUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = UpdateStatusUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateStatusUserReplyValidationError{}
