// Code generated by protoc-gen-gin-http. DO NOT EDIT.
package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
)

import (
	"github.com/gin-gonic/gin"
	"github.com/zngue/zng_app/pkg/router"
	"github.com/zngue/zng_app/pkg/validate"
	"github.com/zngue/zng_app/pkg/bind"
)

// 服务操作
const OperationGinUserList = "api.user.v1.User.List"
const OperationGinUserCreate = "api.user.v1.User.Create"
const OperationGinUserUpdate = "api.user.v1.User.Update"
const OperationGinUserDelete = "api.user.v1.User.Delete"
const OperationGinUserInfo = "api.user.v1.User.Info"
const OperationGinUserUpdateStatus = "api.user.v1.User.UpdateStatus"

// 服务url
const OperationGinUrlUserList = "/v1/user/list"
const OperationGinUrlUserCreate = "/v1/user/create"
const OperationGinUrlUserUpdate = "/v1/user/update"
const OperationGinUrlUserDelete = "/v1/user/delete"
const OperationGinUrlUserInfo = "/v1/user/info"
const OperationGinUrlUserUpdateStatus = "/v1/user/update_status"

//服务接口用户服务

type UserGinHttpService interface {
	List(ctx *gin.Context, req *ListUserRequest) (rs *ListUserReply, err error)
	Create(ctx *gin.Context, req *CreateUserRequest) (rs *CreateUserReply, err error)
	Update(ctx *gin.Context, req *UpdateUserRequest) (rs *UpdateUserReply, err error)
	Delete(ctx *gin.Context, req *DeleteUserRequest) (rs *empty.Empty, err error)
	Info(ctx *gin.Context, req *InfoUserRequest) (rs *InfoUserReply, err error)
	UpdateStatus(ctx *gin.Context, req *UpdateStatusUserRequest) (rs *UpdateStatusUserReply, err error)
}
type UserGinHttpRouterService struct {
	srv    UserGinHttpService
	router *gin.RouterGroup
}

//服务注册用户服务

func (s *UserGinHttpRouterService) Register() []router.IRouter {
	return router.ApiServiceFn(
		router.ApiGetFn(s.router, OperationGinUrlUserList, s.List),
		router.ApiPostFn(s.router, OperationGinUrlUserCreate, s.Create),
		router.ApiPostFn(s.router, OperationGinUrlUserUpdate, s.Update),
		router.ApiPostFn(s.router, OperationGinUrlUserDelete, s.Delete),
		router.ApiGetFn(s.router, OperationGinUrlUserInfo, s.Info),
		router.ApiPostFn(s.router, OperationGinUrlUserUpdateStatus, s.UpdateStatus),
	)
}

func (s *UserGinHttpRouterService) List(ctx *gin.Context) (rs any, err error) {
	var in ListUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserList)
	rs, err = s.srv.List(ctx, &in)
	return
}

func (s *UserGinHttpRouterService) Create(ctx *gin.Context) (rs any, err error) {
	var in CreateUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserCreate)
	rs, err = s.srv.Create(ctx, &in)
	return
}

func (s *UserGinHttpRouterService) Update(ctx *gin.Context) (rs any, err error) {
	var in UpdateUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserUpdate)
	rs, err = s.srv.Update(ctx, &in)
	return
}

func (s *UserGinHttpRouterService) Delete(ctx *gin.Context) (rs any, err error) {
	var in DeleteUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserDelete)
	rs, err = s.srv.Delete(ctx, &in)
	return
}

func (s *UserGinHttpRouterService) Info(ctx *gin.Context) (rs any, err error) {
	var in InfoUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserInfo)
	rs, err = s.srv.Info(ctx, &in)
	return
}

func (s *UserGinHttpRouterService) UpdateStatus(ctx *gin.Context) (rs any, err error) {
	var in UpdateStatusUserRequest
	err = bind.Bind(ctx, &in)
	if err != nil {
		return
	}
	err = validate.Validate(&in)
	if err != nil {
		return
	}
	ctx.Set("operation", OperationGinUserUpdateStatus)
	rs, err = s.srv.UpdateStatus(ctx, &in)
	return
}
func NewUserGinHttpRouterService(router *gin.RouterGroup, srv UserGinHttpService) *UserGinHttpRouterService {
	return &UserGinHttpRouterService{
		srv:    srv,
		router: router,
	}
}
