version: "3.9"
networks:
  zngue_network:
    external: true
services:
  zng_layout:
    build: .
    image: zngue/zng_layout:latest
    restart: always
    container_name: zng_layout
    volumes:
      - ./nacos:/go_run/nacos
    env_file:
      - .env
    ports:
      - "16666:24"
    networks:
      - zngue_network


