// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zngue/zng_app/app"
	"github.com/zngue/zng_layout/internal/api"
	"github.com/zngue/zng_layout/internal/conf"
	"github.com/zngue/zng_layout/internal/cron"
	"github.com/zngue/zng_layout/internal/model"
	"github.com/zngue/zng_layout/internal/server"
	"github.com/zngue/zng_layout/internal/server/http"
	"github.com/zngue/zng_layout/internal/server/http/v1"
)

// Injectors from wire.go:

// initApp init zng_app application.
func initApp(cfg *conf.Bootstrap) (*app.App, func(), error) {
	engine := http.NewHttp()
	httpServer := http.NewService(cfg, engine)
	routerGroup := http.NewHttpGroup(engine)
	router := v1.NewV1Router(routerGroup)
	db, err := model.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	dataDB := model.NewTest(db)
	testApi := api.NewTestApi(router, dataDB)
	routerApi := server.NewRouter(testApi)
	v := server.NewCombineRouter(routerApi)
	v2 := app.NewRouter(v)
	testCron := cron.NewTestCron()
	v3, err := server.NewCron(testCron)
	if err != nil {
		return nil, nil, err
	}
	appApp := app.NewApp(httpServer, v2, v3)
	return appApp, func() {
	}, nil
}
