// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/zngue/zng_app/app"
	"github.com/zngue/zng_layout/internal/api"
	"github.com/zngue/zng_layout/internal/http"
	"github.com/zngue/zng_layout/internal/http/v1"
)

// Injectors from wire.go:

// initApp init zng_app application.
func initApp(port int) (*app.App, func(), error) {
	engine := http.NewHttp()
	routerGroup := http.NewHttpGroup(engine)
	router := v1.NewRouter(routerGroup)
	testApi := api.NewTestApi(router)
	v := http.NewRouter(testApi)
	v2, err := http.NewCron()
	if err != nil {
		return nil, nil, err
	}
	appApp := app.NewApp(port, engine, v, v2)
	return appApp, func() {
	}, nil
}
